apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-nexv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-nexv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-nexv
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-nexv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-nexv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-slvm-tenant/rhtap-demo-app/hacbs-test-project-nexv@sha256:1b3f557b7cab39050b359d1ef8d7aacafaddda8d52c005b3be57da810c1d7b89
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
